### ISSUE TITLE
Remove excerpt or chose what to appear on excerpt

### ISSUE THREAD

**Issue by almeidamarcell** [marcosantonocito/albireo#2]
Hi,

I would like to remove the excerpt from this theme or be allow to pick what is going to appear on the excerption. Because it seems I'm limited to a certain number of characters

**Comment by marcosantonocito** [comment]
Inside partials/loop.hbs I'm using an helper called {{ excerpt }} that, by default, outputs 50 words.
You can change this output changing line 9 and writing:

{{excerpt characters="140"}} that outputs, in this case, 140 characters.

or

{{excerpt words ="50"}} that outputs, in this case, 50 words.
